name: build
on:
   push:
      branches:
      - master
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
      -  name: Checkout
         uses: actions/checkout@v2
      -  name: Set up Maven
         uses: stCarolas/setup-maven@v4.5
         with:
            maven-version: 3.8.7
      -  name: Set up JDK 17
         uses: actions/setup-java@v2
         with:
            distribution: temurin
            java-version: 17
      -  name: Set up cache
         uses: actions/cache@v1
         with:
           path: ~/.m2/repository
           key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
           restore-keys: |
             ${{ runner.os }}-maven-
      -  name: Build
         run: |
            mvn -Dtycho.pomless.aggregator.names=plugins,features,sites clean install
         shell: bash
      - name: Flatten p2 update site
        uses: jbangdev/jbang-action@v0.105.1
        with:
          trust: https://gist.github.com
          script: https://gist.github.com/fbricon/3c718d03f55c3ceba5dea570af4af5f8
          args: ./sites/org.sonatype.m2e.webby.repository
      - name: Upload flat p2 update site
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            ./sites/org.sonatype.m2e.webby.repository/target/flat-repository/*

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./sites/org.sonatype.m2e.webby.repository/target/flat-repository/*
